const PUBLISH_ATTEMPT_WITHOUT_ALLOW_PUBLISH =
  "Publish Attempt Without Allow Publish";
const SCHEDULE_PUBLISH_ATTEMPT_WITHOUT_ALLOW_PUBLISH =
  "Schedule Publish Attempt Without Allow Publish";

export {
  PUBLISH_ATTEMPT_WITHOUT_ALLOW_PUBLISH,
  SCHEDULE_PUBLISH_ATTEMPT_WITHOUT_ALLOW_PUBLISH,
};
