name: cd-dev-stage

on:
  # Uncomment to work on CD in development mode.
  # pull_request:
  #   branches: [ master ]
  push:
    branches:
      - dev
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    env:
      ENV: "dev"

    steps:
      # This Clean step simply checks if there's already a workflow running from the last
      # commit and cancels it if there is. This helps us save on cloud cost in the long run.
      # See https://github.com/rokroskar/workflow-run-cleanup-action for more information.
      - name: Clean
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Auth with Gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_DEV_SA_KEY }}
      - name: Set up Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: zesty-dev
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:dev
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Deploy to Dev
        run: gcloud app deploy app.yaml --quiet --project zesty-dev
      - name: Post Successful Dev Deploy Notification To Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: devops
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://clipart.world/wp-content/uploads/2021/06/Rocket-Ship-clipart-png.png
          SLACK_MESSAGE: |
            Use :eyes: to signal you have seen this message.
            Use :white_check_mark: to signal you have successfully manually tested the deployed changes.
            Use :x: to signal manual tests on deployed changes were unsuccessful and start a thread under this alert describing your remediation steps.
          SLACK_TITLE: Successfully Deployed manager-ui to Dev
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy_to_stage:
    runs-on: ubuntu-latest
    env:
      ENV: "stage"

    steps:
      # This Clean step simply checks if there's already a workflow running from the last
      # commit and cancels it if there is. This helps us save on cloud cost in the long run.
      # See https://github.com/rokroskar/workflow-run-cleanup-action for more information.
      - name: Clean
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Auth with Gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: zesty-stage
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:stage
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Deploy to Staging
        run: gcloud app deploy app.yaml --quiet --project zesty-stage
      - name: Post Successful Stage Deploy Notification To Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: devops
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://clipart.world/wp-content/uploads/2021/06/Rocket-Ship-clipart-png.png
          SLACK_MESSAGE: |
            Use :eyes: to signal you have seen this message.
            Use :white_check_mark: to signal you have successfully manually tested the deployed changes.
            Use :x: to signal manual tests on deployed changes were unsuccessful and start a thread under this alert describing your remediation steps.
          SLACK_TITLE: Successfully Deployed manager-ui to Stage
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  failed_deploy_notification_to_slack:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [deploy_to_dev, deploy_to_stage]
    steps:
      - name: Failed Deploy Notification To Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: code-deploy
          SLACK_COLOR: "#FF0000"
          SLACK_ICON: https://clipart.world/wp-content/uploads/2021/06/Rocket-Ship-clipart-png.png
          SLACK_MESSAGE: "PR merge by ${{ github.actor }} failed to deploy."
          SLACK_TITLE: Deployment Failed for manager-ui
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  success_deploy_notification_to_slack:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [deploy_to_stage]
    steps:
      - name: Success Deploy Notification To Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: code-deploy
          SLACK_COLOR: "#FF0000"
          SLACK_ICON: https://clipart.world/wp-content/uploads/2021/06/Rocket-Ship-clipart-png.png
          SLACK_MESSAGE: "PR merge by ${{ github.actor }} has been deployed to stage."
          SLACK_TITLE: Stage Deployment for manager-ui
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  create_beta_pr:
    runs-on: ubuntu-latest
    needs:
      - deploy_to_dev
      - deploy_to_stage

    steps:
      - uses: actions/checkout@v4
      - name: Create Beta Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: beta
          # base: dev
          title: beta
          # labels:
